spring:
  data:
    mongodb:
      first:
        uri: mongodb://admin:admin@localhost:27017/demo
        host: localhost
        port: 27017
        username: admin
        password: admin
        database: demo
        authentication-database: admin


      second:
        uri: mongodb://admin:admin@localhost:27017/?authSource=admin&authMechanism=SCRAM-SHA-1
        database: another_demo

