spring:
  data:
    mongodb:
      first:
        host: localhost
        port: 27017
        username: myTester
        password: xyz123
        database: test


      second:
        host: localhost
        port: 27017
        username: another
        password: another_p
        database: another_test

