spring:
  datasource:
    subject:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:subject
      username: sa
      password:

    student:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:student
      username: sa
      password: