package io.github.towerking.springbootmybatis.model;

import java.io.Serializable;

public class Student implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STUDENT.ID
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STUDENT.STUDENT_NO
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    private String studentNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STUDENT.STUDENT_NAME
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_STUDENT
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STUDENT.ID
     *
     * @return the value of T_STUDENT.ID
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    public Student withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STUDENT.ID
     *
     * @param id the value for T_STUDENT.ID
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STUDENT.STUDENT_NO
     *
     * @return the value of T_STUDENT.STUDENT_NO
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    public Student withStudentNo(String studentNo) {
        this.setStudentNo(studentNo);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STUDENT.STUDENT_NO
     *
     * @param studentNo the value for T_STUDENT.STUDENT_NO
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo == null ? null : studentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STUDENT.STUDENT_NAME
     *
     * @return the value of T_STUDENT.STUDENT_NAME
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    public Student withStudentName(String studentName) {
        this.setStudentName(studentName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STUDENT.STUDENT_NAME
     *
     * @param studentName the value for T_STUDENT.STUDENT_NAME
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", studentNo=").append(studentNo);
        sb.append(", studentName=").append(studentName);
        sb.append("]");
        return sb.toString();
    }
}