package io.github.towerking.springbootmybatis.mapper;

import io.github.towerking.springbootmybatis.model.Student;
import io.github.towerking.springbootmybatis.model.StudentExample;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    long countByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    int deleteByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    @Delete({
        "delete from T_STUDENT",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    @Insert({
        "insert into T_STUDENT (STUDENT_NO, STUDENT_NAME)",
        "values (#{studentNo,jdbcType=VARCHAR}, #{studentName,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="CALL IDENTITY()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    List<Student> selectByExampleWithRowbounds(StudentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    List<Student> selectByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    @Select({
        "select",
        "ID, STUDENT_NO, STUDENT_NAME",
        "from T_STUDENT",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("io.github.towerking.springbootmybatis.mapper.StudentMapper.BaseResultMap")
    Student selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") Student record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    int updateByExample(@Param("record") Student record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STUDENT
     *
     * @mbg.generated Sun Jun 30 07:52:36 CST 2019
     */
    @Update({
        "update T_STUDENT",
        "set STUDENT_NO = #{studentNo,jdbcType=VARCHAR},",
          "STUDENT_NAME = #{studentName,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Student record);
}